# -*- coding: utf-8 -*-
"""Perform Data Cleaning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tRSPRhWo19o1PXN6q1L37VTHaqTxXkhi
"""

import pandas as pd

gender=pd.read_csv('/content/gender_submission.csv')

#clean the dataset by removing missing value for a gender
gender.dropna(inplace=True) #remove empty cell
gender.drop_duplicates(inplace=True) #remove duplicates

print(gender.to_string())



test=pd.read_csv('/content/test.csv')

#clean the dataset by removing missing value for a test
test.dropna(inplace=True) #remove empty cell
test.drop_duplicates(inplace=True) #remove duplicates
x=test["Age"].mean()
test["Age"].fillna(x,inplace=True)

print(test.to_string())




train=pd.read_csv('/content/train.csv')

#clean the dataset by removing missing value for a train
train.dropna(inplace=True) #remove empty cell
train.drop_duplicates(inplace=True) #remove duplicates
x=train["Age"].mean()
train["Age"].fillna(x,inplace=True)

print(train.to_string())